### ISSUE TITLE
Error when attaching / detaching multiple instances

### ISSUE THREAD

**Issue by fbaptista** [3dgiordano/taurus#2]
Steps to reproduce: 

bzt remote attach SS1
bzt remote attach SS2
bzt remote detach SS2
bzt remote list -> ERROR
(venv) fabians-air:venv fabianbaptista$ bzt remote list
Remote List
TypeError: string indices must be integers

**Comment by 3dgiordano** [comment]
The problem is related with a intermediate state, the issue issue is known and is to be investigated

**Comment by 3dgiordano** [comment]
Duplicated issue
#3
