### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by fbaptista** [3dgiordano/taurus#3]
hen the instances that are being attached are listed at a certain moment, an error occurs.
TypeError: string indices must be integers

**Comment by fbaptista** [comment]
Steps to reproduce:    
bzt remote attach SS1 
bzt remote attach SS2 
bzt remote detach SS2 
bzt remote list -> ERROR 
(venv) fabians-air:venv fabianbaptista$ 
bzt remote list Remote List 
TypeError: string indices must be integers

**Comment by 3dgiordano** [comment]
I edited the issue to separate them because Fabian mistakenly registered two issues in one.

**Comment by 3dgiordano** [comment]
the error related to TypeError: string indices must be integers was solved.
the problem was related to intermediate state in the startup process of the service, solved in the lamda service now.
