### ISSUE TITLE
Cumulative stats in Taurus live report starts only after the first "sampler" / test case ends. 

### ISSUE THREAD

**Issue by 3dgiordano** [3dgiordano/taurus#4]
@fbaptista mention:
Cumulative stats in Taurus live report starts only after the first "sampler" / test case ends. it should be reporting each transaction (test / steps) instead.

**Comment by fbaptista** [comment]
why is this assigned to me? didn't understand

**Comment by 3dgiordano** [comment]
sorry, selection error.

related to the issue reportered, the actual apiritif + taurus they do not update in real time, I will investigate if it is possible to force a faster update.
